<?php

/*
 * Focus Theme addon for Bear CMS
 * https://github.com/bearcms/focus-theme-addon
 * Copyright (c) Amplilabs Ltd.
 * Free to use under the MIT license.
 */

return [
    'homePageLogoImageContainerCSS' => '{"margin-bottom":"20px"}',
    'homePageTitleVisibility' => '1',
    'homePageTitleCSS' => '{"font-family":"googlefonts:Open Sans","font-size":"40px","font-weight":"bold","color":"#ffffff"}',
    'homePageTitleContainerCSS' => '{"margin-bottom":"20px"}',
    'homePageDescriptionVisibility' => '1',
    'homePageDescriptionCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"15px"}',
    'homePageDescriptionContainerCSS' => '{"margin-bottom":"20px"}',
    'homePageContainerCSS' => '{"background-color":"rgba(0,0,0,0.8)","max-width":"800px","width":"100%","padding-top":"20px","padding-bottom":"20px","padding-left":"20px","padding-right":"20px","margin-left":"auto","margin-right":"auto","margin-top":"30px","margin-bottom":"30px","border-bottom-left-radius":"10px","border-bottom-right-radius":"10px","border-top-left-radius":"10px","border-top-right-radius":"10px"}',
    'homePageContentElementsHeadingLargeCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgb(234, 115, 51)"}',
    'homePageContentElementsHeadingMediumCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"22px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgba(234, 115, 51,0.8)"}',
    'homePageContentElementsHeadingSmallCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"18px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgba(234, 115, 51, 0.6)"}',
    'homePageContentElementsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsTextLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsNavigationItemLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsImageGalleryImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsVideoCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsCommentCSS' => '{"margin-bottom":"10px"}',
    'homePageContentElementsCommentsAuthorNameCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","text-decoration":"underline","margin-bottom":"4px"}',
    'homePageContentElementsCommentsAuthorImageCSS' => '{"width":"50px","height":"50px","margin-right":"8px","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsDateCSS' => '{"color":"#aaa","font-family":"Arial","font-size":"12px","line-height":"180%"}',
    'homePageContentElementsCommentsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsCommentsTextLinksCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsCommentsTextInputCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","padding-left":"15px","padding-right":"15px","padding-top":"10px","padding-bottom":"10px","width":"100%","height":"80px","border-top":"","border-bottom":"","border-left":"","border-right":"","border-top:hover":"","border-bottom:hover":"","border-left:hover":"","border-right:hover":"","border-top:active":"","border-bottom:active":"","border-left:active":"","border-right:active":"","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsSendButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","margin-top":"10px"}',
    'homePageContentElementsCommentsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'homePageContentElementsHtmlCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsHtmlLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsBlogPostsPostTitleCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"22px","text-align":"left","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsBlogPostsPostDateCSS' => '{"color":"#eeeeee","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsBlogPostsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageBackToHomeButtonCSS' => '{"background-image":"url(addon:bearcms\/focus-theme-addon:assets\/s1\/home-button.svg)","width":"42px","height":"42px","margin-top":"15px","margin-bottom":"15px","margin-left":"auto","margin-right":"auto","background-position":"center center","background-size":"contain"}',
    'pageBackToHomeButtonContainerCSS' => '{"background-color":"rgba(0,0,0,0.8)","max-width":"800px","width":"100%","margin-left":"auto","margin-right":"auto","border-bottom-left-radius":"10px","border-bottom-right-radius":"10px"}',
    'pageContentElementsHeadingLargeCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgb(234, 115, 51)"}',
    'pageContentElementsHeadingMediumCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"22px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgba(234, 115, 51,0.8)"}',
    'pageContentElementsHeadingSmallCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"18px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgba(234, 115, 51, 0.6)"}',
    'pageContentElementsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsTextLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsNavigationItemLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsImageGalleryImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsVideoCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsCommentCSS' => '{"margin-bottom":"10px"}',
    'pageContentElementsCommentsAuthorNameCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","text-decoration":"underline","margin-bottom":"4px"}',
    'pageContentElementsCommentsAuthorImageCSS' => '{"width":"50px","height":"50px","margin-right":"8px","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsDateCSS' => '{"color":"#aaa","font-family":"Arial","font-size":"12px","line-height":"180%"}',
    'pageContentElementsCommentsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsCommentsTextLinksCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsCommentsTextInputCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","padding-left":"15px","padding-right":"15px","padding-top":"10px","padding-bottom":"10px","width":"100%","height":"80px","border-top":"","border-bottom":"","border-left":"","border-right":"","border-top:hover":"","border-bottom:hover":"","border-left:hover":"","border-right:hover":"","border-top:active":"","border-bottom:active":"","border-left:active":"","border-right:active":"","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsSendButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","margin-top":"10px"}',
    'pageContentElementsCommentsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageContentElementsHtmlCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsHtmlLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsBlogPostsPostTitleCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"22px","text-align":"left","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsBlogPostsPostDateCSS' => '{"color":"#eeeeee","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsBlogPostsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageContentElementsContainerCSS' => '{"background-color":"rgba(0,0,0,0.8)","max-width":"800px","width":"100%","padding-top":"20px","padding-bottom":"20px","padding-left":"20px","padding-right":"20px","margin-left":"auto","margin-right":"auto","margin-top":"30px","margin-bottom":"30px","border-bottom-left-radius":"10px","border-bottom-right-radius":"10px","border-top-left-radius":"10px","border-top-right-radius":"10px"}',
    'windowCSS' => '{"background-color":"#000000","background-image":"url(addon:bearcms\/focus-theme-addon:assets\/s1\/1.jpg)","background-position":"top center","background-repeat":"no-repeat","background-attachment":"fixed","background-size":"cover"}',
    'blogPostPageTitleCSS' => '{"color":"#ffffff","font-family":"googlefonts:Open Sans","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0","margin-left":"-20px","padding-left":"18px","border-left":"2px solid rgb(234, 115, 51)"}',
    'blogPostPageDateCSS' => '{"color":"rgba(255,255,255,0.5)","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'blogPostPageContentCSS' => '{"padding-top":"15px"}',
];
