<?php

/*
 * Focus Theme addon for Bear CMS
 * https://github.com/bearcms/focus-theme-addon
 * Copyright (c) Amplilabs Ltd.
 * Free to use under the MIT license.
 */

return [
    'homePageLogoImageContainerCSS' => '{"margin-bottom":"20px","text-align":"center"}',
    'homePageTitleVisibility' => '1',
    'homePageTitleCSS' => '{"font-family":"googlefonts:Vollkorn SC","font-size":"50px","font-weight":"bold","color":"#000"}',
    'homePageTitleContainerCSS' => '{"margin-bottom":"20px","text-align":"center"}',
    'homePageDescriptionVisibility' => '1',
    'homePageDescriptionCSS' => '{"color":"#000","font-family":"googlefonts:Vollkorn SC","font-size":"20px"}',
    'homePageDescriptionContainerCSS' => '{"margin-bottom":"20px","text-align":"center"}',
    'homePageContentElementsHeadingLargeCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"38px","line-height":"140%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0","text-align":"center"}',
    'homePageContentElementsHeadingMediumCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"32px","line-height":"140%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0","text-align":"center"}',
    'homePageContentElementsHeadingSmallCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"24px","line-height":"140%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0","text-align":"center"}',
    'homePageContentElementsTextCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsTextLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsNavigationItemLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsImageGalleryImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsVideoCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsCommentCSS' => '{"margin-bottom":"10px"}',
    'homePageContentElementsCommentsAuthorNameCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","text-decoration":"underline","margin-bottom":"4px"}',
    'homePageContentElementsCommentsAuthorImageCSS' => '{"width":"50px","height":"50px","margin-right":"8px","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsDateCSS' => '{"color":"#aaa","font-family":"Arial","font-size":"12px","line-height":"180%"}',
    'homePageContentElementsCommentsTextCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsCommentsTextLinksCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsCommentsTextInputCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","padding-left":"15px","padding-right":"15px","padding-top":"10px","padding-bottom":"10px","width":"100%","height":"80px","border-top":"","border-bottom":"","border-left":"","border-right":"","border-top:hover":"","border-bottom:hover":"","border-left:hover":"","border-right:hover":"","border-top:active":"","border-bottom:active":"","border-left:active":"","border-right:active":"","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","border-top":"1px solid #000000","border-bottom":"1px solid #000000","border-left":"1px solid #000000","border-right":"1px solid #000000"}',
    'homePageContentElementsCommentsSendButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color:hover":"#000000","background-color:active":"#000000","color:hover":"#ffffff","color:active":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","margin-top":"10px","border-top":"1px solid #000000","border-bottom":"1px solid #000000","border-left":"1px solid #000000","border-right":"1px solid #000000"}',
    'homePageContentElementsCommentsSendButtonWaitingCSS' => '{"background-color":"#000000","color":"#ffffff"}',
    'homePageContentElementsCommentsShowMoreButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'homePageContentElementsHtmlCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsHtmlLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsBlogPostsPostTitleCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"22px","text-align":"left","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsBlogPostsPostDateCSS' => '{"color":"#333333","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsBlogPostsShowMoreButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'homePageContainerCSS' => '{"max-width":"800px","width":"100%","padding-top":"30px","padding-bottom":"30px","padding-left":"15px","padding-right":"15px","margin-left":"auto","margin-right":"auto"}',
    'pageBackToHomeButtonCSS'=>'{"background-image":"url(addon:bearcms\/focus-theme-addon:assets\/s2\/home-button.svg)","width":"42px","height":"42px","margin-top":"15px","margin-bottom":"15px","margin-left":"auto","margin-right":"auto","background-position":"center center","background-size":"contain","background-repeat":"no-repeat","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","background-color:hover":"#111111","background-color:active":"#000000"}',
    'pageContentElementsHeadingLargeCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"38px","line-height":"140%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'pageContentElementsHeadingMediumCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"32px","line-height":"140%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'pageContentElementsHeadingSmallCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"24px","line-height":"140%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'pageContentElementsTextCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsTextLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsNavigationItemLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsImageGalleryImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsVideoCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsCommentCSS' => '{"margin-bottom":"10px"}',
    'pageContentElementsCommentsAuthorNameCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","text-decoration":"underline","margin-bottom":"4px"}',
    'pageContentElementsCommentsAuthorImageCSS' => '{"width":"50px","height":"50px","margin-right":"8px","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsDateCSS' => '{"color":"#aaa","font-family":"Arial","font-size":"12px","line-height":"180%"}',
    'pageContentElementsCommentsTextCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsCommentsTextLinksCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsCommentsTextInputCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","padding-left":"15px","padding-right":"15px","padding-top":"10px","padding-bottom":"10px","width":"100%","height":"80px","border-top":"","border-bottom":"","border-left":"","border-right":"","border-top:hover":"","border-bottom:hover":"","border-left:hover":"","border-right:hover":"","border-top:active":"","border-bottom:active":"","border-left:active":"","border-right:active":"","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","border-top":"1px solid #dddddd","border-bottom":"1px solid #dddddd","border-left":"1px solid #dddddd","border-right":"1px solid #dddddd"}',
    'pageContentElementsCommentsSendButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color:hover":"#dddddd","background-color:active":"#dddddd","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","margin-top":"10px","border-top":"1px solid #dddddd","border-bottom":"1px solid #dddddd","border-left":"1px solid #dddddd","border-right":"1px solid #dddddd"}',
    'pageContentElementsCommentsShowMoreButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageContentElementsHtmlCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsHtmlLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsBlogPostsPostTitleCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"22px","text-align":"left","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsBlogPostsPostDateCSS' => '{"color":"#333333","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsBlogPostsShowMoreButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageContentElementsContainerCSS' => '{"background-color":"#f5f5f5","max-width":"800px","width":"100%","padding-top":"20px","padding-bottom":"20px","padding-left":"20px","padding-right":"20px","margin-left":"auto","margin-right":"auto","margin-top":"30px","margin-bottom":"30px","border-top-left-radius":"10px","border-top-right-radius":"10px","border-bottom-left-radius":"10px","border-bottom-right-radius":"10px","box-shadow":"0 0 5px 0 rgba(0,0,0,0.5)"}',
    'windowCSS' => '{"background-color":"#000000","background-image":"url(addon:bearcms\/focus-theme-addon:assets\/s2\/1.jpg)","background-position":"top center","background-repeat":"no-repeat","background-attachment":"fixed","background-size":"cover"}',
    'blogPostPageTitleCSS' => '{"color":"#000000","font-family":"googlefonts:Vollkorn SC","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'blogPostPageDateCSS' => '{"color":"#333333","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'blogPostPageContentCSS' => '{"padding-top":"15px"}',
];
