<?php

/*
 * Focus Theme addon for Bear CMS
 * https://github.com/bearcms/focus-theme-addon
 * Copyright (c) Amplilabs Ltd.
 * Free to use under the MIT license.
 */

return [
    'homePageLogoImageContainerCSS' => '{"margin-bottom":"20px"}',
    'homePageTitleVisibility' => '1',
    'homePageTitleCSS' => '{"font-family":"googlefonts:Ubuntu","font-size":"40px","font-weight":"bold","color":"#fff"}',
    'homePageTitleContainerCSS' => '{"margin-bottom":"20px"}',
    'homePageDescriptionVisibility' => '1',
    'homePageDescriptionCSS' => '{"color":"#fff","font-family":"googlefonts:Ubuntu","font-size":"15px"}',
    'homePageDescriptionContainerCSS' => '{"margin-bottom":"20px"}',
    'homePageContainerCSS' => '{"max-width":"800px","width":"100%","padding-top":"30px","padding-bottom":"30px","padding-left":"15px","padding-right":"15px","margin-left":"auto","margin-right":"auto"}',
    'homePageContentElementsHeadingLargeCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'homePageContentElementsHeadingMediumCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"22px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'homePageContentElementsHeadingSmallCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"18px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'homePageContentElementsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsTextLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsNavigationItemLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsImageGalleryImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsVideoCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsCommentCSS' => '{"margin-bottom":"10px"}',
    'homePageContentElementsCommentsAuthorNameCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","text-decoration":"underline","margin-bottom":"4px"}',
    'homePageContentElementsCommentsAuthorImageCSS' => '{"width":"50px","height":"50px","margin-right":"8px","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsDateCSS' => '{"color":"#aaa","font-family":"Arial","font-size":"12px","line-height":"180%"}',
    'homePageContentElementsCommentsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsCommentsTextLinksCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsCommentsTextInputCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","padding-left":"15px","padding-right":"15px","padding-top":"10px","padding-bottom":"10px","width":"100%","height":"80px","border-top":"","border-bottom":"","border-left":"","border-right":"","border-top:hover":"","border-bottom:hover":"","border-left:hover":"","border-right:hover":"","border-top:active":"","border-bottom:active":"","border-left:active":"","border-right:active":"","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'homePageContentElementsCommentsSendButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","margin-top":"10px"}',
    'homePageContentElementsCommentsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'homePageContentElementsHtmlCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsHtmlLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsBlogPostsPostTitleCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"22px","text-align":"left","line-height":"180%","text-decoration":"underline"}',
    'homePageContentElementsBlogPostsPostDateCSS' => '{"color":"#eeeeee","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'homePageContentElementsBlogPostsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageBackToHomeButtonCSS'=>'{"background-image":"url(addon:bearcms\/focus-theme-addon:assets\/s4\/home-button.svg)","width":"44px","height":"44px","margin-top":"15px","margin-bottom":"15px","margin-left":"auto","margin-right":"auto","background-position":"center center","background-size":"contain","background-repeat":"no-repeat","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","border-left":"2px solid rgba(255,255,255,0)","border-right":"2px solid rgba(255,255,255,0)","border-top":"2px solid rgba(255,255,255,0)","border-bottom":"2px solid rgba(255,255,255,0)","border-left:hover":"2px solid #fff","border-right:hover":"2px solid #fff","border-top:hover":"2px solid #fff","border-bottom:hover":"2px solid #fff","border-left:active":"2px solid #fff","border-right:active":"2px solid #fff","border-top:active":"2px solid #fff","border-bottom:active":"2px solid #fff"}',
    'pageContentElementsHeadingLargeCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'pageContentElementsHeadingMediumCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"22px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'pageContentElementsHeadingSmallCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"18px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'pageContentElementsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsTextLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsLinkCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsNavigationItemLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsImageGalleryImageCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsVideoCSS' => '{"border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsCommentCSS' => '{"margin-bottom":"10px"}',
    'pageContentElementsCommentsAuthorNameCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","text-decoration":"underline","margin-bottom":"4px"}',
    'pageContentElementsCommentsAuthorImageCSS' => '{"width":"50px","height":"50px","margin-right":"8px","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsDateCSS' => '{"color":"#aaa","font-family":"Arial","font-size":"12px","line-height":"180%"}',
    'pageContentElementsCommentsTextCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsCommentsTextLinksCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsCommentsTextInputCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"180%","padding-left":"15px","padding-right":"15px","padding-top":"10px","padding-bottom":"10px","width":"100%","height":"80px","border-top":"","border-bottom":"","border-left":"","border-right":"","border-top:hover":"","border-bottom:hover":"","border-left:hover":"","border-right:hover":"","border-top:active":"","border-bottom:active":"","border-left:active":"","border-right:active":"","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px"}',
    'pageContentElementsCommentsSendButtonCSS' => '{"color":"#000000","font-family":"Arial","font-size":"14px","line-height":"42px","padding-left":"15px","padding-right":"15px","height":"42px","background-color":"#ffffff","border-top-left-radius":"2px","border-top-right-radius":"2px","border-bottom-left-radius":"2px","border-bottom-right-radius":"2px","margin-top":"10px"}',
    'pageContentElementsCommentsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageContentElementsHtmlCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsHtmlLinkCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsBlogPostsPostTitleCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"22px","text-align":"left","line-height":"180%","text-decoration":"underline"}',
    'pageContentElementsBlogPostsPostDateCSS' => '{"color":"#eeeeee","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'pageContentElementsBlogPostsShowMoreButtonCSS' => '{"color":"#ffffff","font-family":"Arial","font-size":"14px","line-height":"180%","text-decoration":"underline","margin-bottom":"5px"}',
    'pageContentElementsContainerCSS' => '{"max-width":"800px","width":"100%","padding-top":"30px","padding-bottom":"30px","padding-left":"15px","padding-right":"15px","margin-left":"auto","margin-right":"auto"}',
    'windowCSS' => '{"background-color":"#000000","background-image":"url(addon:bearcms\/focus-theme-addon:assets\/s4\/1.jpg)","background-position":"top center","background-repeat":"no-repeat","background-attachment":"fixed","background-size":"cover"}',
    'blogPostPageTitleCSS' => '{"color":"#ffffff","font-family":"googlefonts:Ubuntu","font-size":"28px","line-height":"180%","margin-top":"0","margin-right":"0","margin-bottom":"0","margin-left":"0"}',
    'blogPostPageDateCSS' => '{"color":"rgba(255,255,255,0.5)","font-family":"Arial","font-size":"14px","line-height":"180%"}',
    'blogPostPageContentCSS' => '{"padding-top":"15px"}',
];
